### ISSUE TITLE
Py38-sqlite3 is missing

### ISSUE THREAD

**Issue by mkohanim** [rl1131/udi-wemo-poly#3]
Please install py38-sqlite3 package as part of the install.sh. This package is necessary for BSD v13.
thank you.

**Comment by rl1131** [comment]
Hi Michel,
sqlite3 is supposed to be a part of the Python Standard Library.  If Python is installed, so should sqlite3 be installed.
Is there some reason why this isn't the case on the Polisy?

**Comment by rl1131** [comment]
FYI, a list of Standard modules is here:  https://docs.python.org/3/library/

**Comment by mkohanim** [comment]
Hi Robert,

Thank you for getting back. It seems that sqlite3 is not part of python 38. At least not by default on FreeBSD.

With kind regards,

******************************
Michel Kohanim

(p) 818.631.0333
http://www.universal-devices.com
******************************
________________________________

**Comment by rl1131** [comment]
Hi Michel,

sqlite3 has been a part of the Python Standard Library since 2.5 (way before 3.8).  Given the issue with 3.8, I checked and it is supposed to be a part of the Standard Library for 3.8 too.  https://docs.python.org/3.8/library/

Why doesn't the Polisy installation of Python have sqlite3 in the Standard Library?

The reason I am hesitant to make this change is that adding this change ties this package to Polisy running Python 3.8.  Plus, making this change appears to be solving the symptom and not the root problem.

Let me know your thoughts, if you still think this is the right way to solve the issue, I'll add it to requirements.txt and test it out.

-Robert

**Comment by mkohanim** [comment]
Hi Robert,

Thank you. I’ll make sure it gets installed by default. I am not sure what has changed but it’s no longer part of py38 on FreeBSD. It has to be explicitly installed.

With kind regards,

******************************
  Michel Kohanim
             CEO

  (p) 818.631.0333
  http://www.universal-devices.com<http://www.universal-devices.com/>
******************************
